#Service
#nginx-svc-np.yml
apiVersion: v1
kind: Service
metadata:
  name: my-jenkins-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
    - nodePort: 32000
      port: 80
      targetPort: 8999

